name: CI

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version:
          - "oldstable"
          - "stable"
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1

      - name: Test
        run: go test -v -race -timeout=60s ./...
